name: Testing

on:
  workflow_dispatch:
  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous workflow timestamp
        uses: dpguthrie/last-workflow-created-at@v0.1.2
        id: last_created_at
